/* tslint:disable */
/* eslint-disable */
/**
 * RADON CTT Server API
 * This is API of the RADON Continuous Testing Tool (CTT) Server: <a href=\"https://github.com/radon-h2020/radon-ctt\">https://github.com/radon-h2020/radon-ctt<a/>
 *
 * OpenAPI spec version: 1.0.0-oas3
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import globalAxios, { AxiosPromise, AxiosInstance } from 'axios';
import { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
import { Deployment } from '../models';
import { POSTDeployment } from '../models';
/**
 * DeploymentApi - axios parameter creator
 * @export
 */
export const DeploymentApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Creates a deployment
         * @param {POSTDeployment} [body] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createDeployment: async (body?: POSTDeployment, options: any = {}): Promise<RequestArgs> => {
            const localVarPath = `/deployment`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.query) {
                query.set(key, options.query[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            const needsSerialization = (typeof body !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.data =  needsSerialization ? JSON.stringify(body !== undefined ? body : {}) : (body || "");

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * Deletes the test artifact with the given UUID and all elements depending on it
         * @summary Delete a deployment
         * @param {string} deploymentUuid UUID of the deployment to delete
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteDeploymentByUuid: async (deploymentUuid: string, options: any = {}): Promise<RequestArgs> => {
            // verify required parameter 'deploymentUuid' is not null or undefined
            if (deploymentUuid === null || deploymentUuid === undefined) {
                throw new RequiredError('deploymentUuid','Required parameter deploymentUuid was null or undefined when calling deleteDeploymentByUuid.');
            }
            const localVarPath = `/deployment/{deployment_uuid}`
                .replace(`{${"deployment_uuid"}}`, encodeURIComponent(String(deploymentUuid)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.query) {
                query.set(key, options.query[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Retrieve a deployment
         * @param {string} deploymentUuid UUID of the deployment to return
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getDeploymentByUuid: async (deploymentUuid: string, options: any = {}): Promise<RequestArgs> => {
            // verify required parameter 'deploymentUuid' is not null or undefined
            if (deploymentUuid === null || deploymentUuid === undefined) {
                throw new RequiredError('deploymentUuid','Required parameter deploymentUuid was null or undefined when calling getDeploymentByUuid.');
            }
            const localVarPath = `/deployment/{deployment_uuid}`
                .replace(`{${"deployment_uuid"}}`, encodeURIComponent(String(deploymentUuid)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.query) {
                query.set(key, options.query[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Get all deployments
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getDeployments: async (options: any = {}): Promise<RequestArgs> => {
            const localVarPath = `/deployment`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.query) {
                query.set(key, options.query[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * DeploymentApi - functional programming interface
 * @export
 */
export const DeploymentApiFp = function(configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Creates a deployment
         * @param {POSTDeployment} [body] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async createDeployment(body?: POSTDeployment, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await DeploymentApiAxiosParamCreator(configuration).createDeployment(body, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * Deletes the test artifact with the given UUID and all elements depending on it
         * @summary Delete a deployment
         * @param {string} deploymentUuid UUID of the deployment to delete
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async deleteDeploymentByUuid(deploymentUuid: string, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Deployment>> {
            const localVarAxiosArgs = await DeploymentApiAxiosParamCreator(configuration).deleteDeploymentByUuid(deploymentUuid, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @summary Retrieve a deployment
         * @param {string} deploymentUuid UUID of the deployment to return
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getDeploymentByUuid(deploymentUuid: string, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Deployment>> {
            const localVarAxiosArgs = await DeploymentApiAxiosParamCreator(configuration).getDeploymentByUuid(deploymentUuid, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @summary Get all deployments
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getDeployments(options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<Deployment>>> {
            const localVarAxiosArgs = await DeploymentApiAxiosParamCreator(configuration).getDeployments(options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
    }
};

/**
 * DeploymentApi - factory interface
 * @export
 */
export const DeploymentApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    return {
        /**
         * 
         * @summary Creates a deployment
         * @param {POSTDeployment} [body] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createDeployment(body?: POSTDeployment, options?: any): AxiosPromise<void> {
            return DeploymentApiFp(configuration).createDeployment(body, options).then((request) => request(axios, basePath));
        },
        /**
         * Deletes the test artifact with the given UUID and all elements depending on it
         * @summary Delete a deployment
         * @param {string} deploymentUuid UUID of the deployment to delete
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteDeploymentByUuid(deploymentUuid: string, options?: any): AxiosPromise<Deployment> {
            return DeploymentApiFp(configuration).deleteDeploymentByUuid(deploymentUuid, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Retrieve a deployment
         * @param {string} deploymentUuid UUID of the deployment to return
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getDeploymentByUuid(deploymentUuid: string, options?: any): AxiosPromise<Deployment> {
            return DeploymentApiFp(configuration).getDeploymentByUuid(deploymentUuid, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Get all deployments
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getDeployments(options?: any): AxiosPromise<Array<Deployment>> {
            return DeploymentApiFp(configuration).getDeployments(options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * DeploymentApi - object-oriented interface
 * @export
 * @class DeploymentApi
 * @extends {BaseAPI}
 */
export class DeploymentApi extends BaseAPI {
    /**
     * 
     * @summary Creates a deployment
     * @param {POSTDeployment} [body] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DeploymentApi
     */
    public createDeployment(body?: POSTDeployment, options?: any) {
        return DeploymentApiFp(this.configuration).createDeployment(body, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * Deletes the test artifact with the given UUID and all elements depending on it
     * @summary Delete a deployment
     * @param {string} deploymentUuid UUID of the deployment to delete
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DeploymentApi
     */
    public deleteDeploymentByUuid(deploymentUuid: string, options?: any) {
        return DeploymentApiFp(this.configuration).deleteDeploymentByUuid(deploymentUuid, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * 
     * @summary Retrieve a deployment
     * @param {string} deploymentUuid UUID of the deployment to return
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DeploymentApi
     */
    public getDeploymentByUuid(deploymentUuid: string, options?: any) {
        return DeploymentApiFp(this.configuration).getDeploymentByUuid(deploymentUuid, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * 
     * @summary Get all deployments
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DeploymentApi
     */
    public getDeployments(options?: any) {
        return DeploymentApiFp(this.configuration).getDeployments(options).then((request) => request(this.axios, this.basePath));
    }
}
