/* tslint:disable */
/* eslint-disable */
/**
 * RADON CTT Server API
 * This is API of the RADON Continuous Testing Tool (CTT) Server: <a href=\"https://github.com/radon-h2020/radon-ctt\">https://github.com/radon-h2020/radon-ctt<a/>
 *
 * OpenAPI spec version: 1.0.0-oas3
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface POSTTestArtifact
 */
export interface POSTTestArtifact {
    /**
     * 
     * @type {string}
     * @memberof POSTTestArtifact
     */
    project_uuid: any;
    /**
     * 
     * @type {string}
     * @memberof POSTTestArtifact
     */
    sut_tosca_path: any;
    /**
     * 
     * @type {string}
     * @memberof POSTTestArtifact
     */
    ti_tosca_path: any;
    /**
     * 
     * @type {string}
     * @memberof POSTTestArtifact
     */
    sut_inputs_path?: any;
    /**
     * 
     * @type {string}
     * @memberof POSTTestArtifact
     */
    ti_inputs_path?: any;
}
